### ISSUE TITLE
Timelapse-Screen mit Grafik ausbauen

### ISSUE THREAD

**Issue by zahu69** [Fabiansson/CamSlider#12]
Bezeichnung der Achsen - evtl. mit Legende X=rot  / Y=grün / Z=blau
Startzeit
Verbleibende Zeit
Endzeit
Bild x von y
Shutterspeed / ISO / A
evtl. noch das zuletzt analysierte Bild mit Hystogramm anzeigen um zu sehen ob man den Referenzwert korrigieren muss...
Dazu dann auch zwei Tasten Ref +100 und ref -100 oä.

**Comment by Fabiansson** [comment]
ShutterSpeed / ISO, Bildvorschau und Korrekturbuttons nur bei Timelapse mit "Brightness Control" nötig
