### ISSUE TITLE
Timelapsemode-General Options-Zusatzfeld "Pricessing Time"

### ISSUE THREAD

**Issue by zahu69** [Fabiansson/CamSlider#13]
Je nach Kameramodell, wie schnell die Kamera die Bilder speichern kann darf die max Belichtungszeit vielleicht 1-2sec kleiner sein als das Interwall.
Zusatzfeld Processing Time mit default Wert auf 2sec.
Die Maximale Belcihtungszeit wird dann aus dem beiden Parametern Interval und Proc-Time berechnet und die Matrix dann so definiert, dass nach Erreichen der Max Belichtungszeit automatisch der ISO-Wert erhöht wird.

**Comment by Fabiansson** [comment]
Solved with #33
