### ISSUE TITLE
Services-reboot

### ISSUE THREAD

**Issue by zahu69** [Fabiansson/CamSlider#14]
Wenn man alles neu initialisieren möchte, ist es ineffizeint den ganzen Raspi neu zu starten.
Alle Motoren werden dann entblockt - Die Kamera saust nach unten - Die Wlan-Verbindung geht verloren und uU. hat man dann wieder automatisch eine falsche Wlan-Verbindung zu einem anderen Reouter und muss diese dann zuerst umswitchen.
Restart Slider-Services

**Comment by Fabiansson** [comment]
Solved by 8fe4b61c8fc5add9ebdcd7fc6bad92fee44c109a
